version: '3.7'

services:
  eventstore.db:
    image: eventstore/eventstore:22.10.3-alpha-arm64v8 # For Apple M Chips
    # image: eventstore/eventstore:21.6.0-buster-slim # For ARM Chips
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /c/data/eventstore/data
      - type: volume
        source: eventstore-volume-logs
        target: /c/data/eventstore/logs
volumes:
  eventstore-volume-data:
  eventstore-volume-logs: